name: TLamPlayerReport
version: 1.0.0
main: com.tlamplayerreport.ReportPlugin
api-version: '1.16'
author: TranLam (Midnight)
description: Advanced player and bug reporting system with multi-language support
website: https://github.com/TranLam

commands:
  report:
    description: Open the report menu
    usage: /report
    aliases: [reportplayer, reportbug]
  
  tlamplayerreportadmin:
    description: Admin commands for managing reports
    usage: |
      /tlamplayerreportadmin help - Show help menu
      /tlamplayerreportadmin list [page] - List all reports
      /tlamplayerreportadmin view <id> - View report details
      /tlamplayerreportadmin delete <id> - Delete a report
      /tlamplayerreportadmin clear - Clear all reports
      /tlamplayerreportadmin reload - Reload configuration
    permission: tlamplayerreport.admin
    aliases: [tlpradmin, tlpr, tlamplayerreport, reportadmin]

permissions:
  tlamplayerreport.use:
    description: Use report command (legacy name)
    default: true
  
  tlamplayerreport.report:
    description: Allows using the report command
    default: true
  
  tlamplayerreport.admin:
    description: Access to all admin features
    default: op
    children:
      tlamplayerreport.admin.view: true
      tlamplayerreport.admin.delete: true
      tlamplayerreport.admin.clear: true
      tlamplayerreport.admin.reload: true
      tlamplayerreport.notify: true
      tlamplayerreport.bypass.cooldown: true
      tlamplayerreport.bypass.limit: true
  
  tlamplayerreport.admin.view:
    description: View all reports
    default: op
  
  tlamplayerreport.admin.delete:
    description: Delete specific reports
    default: op
  
  tlamplayerreport.admin.clear:
    description: Clear all reports
    default: op
  
  tlamplayerreport.admin.reload:
    description: Reload plugin configuration
    default: op
  
  tlamplayerreport.notify:
    description: Receive notifications when new reports are submitted
    default: op
  
  tlamplayerreport.bypass.cooldown:
    description: Bypass report cooldown
    default: op
  
  tlamplayerreport.bypass.limit:
    description: Bypass report limits
    default: op
  
  tlamplayerreport.view.own:
    description: View own submitted reports
    default: true